#version 460 core
layout(local_size_x = 128) in;

struct Particle {
  vec4 position;
  vec4 velocity;
};

layout(std430, binding = 0) buffer layout_particles_in {
  Particle particles_in[];
};

layout(std430, binding = 1) buffer layout_particles_out {
  Particle particles_out[];
};

void main() {
  uint gidx = gl_GlobalInvocationID.x;

  // swap particle buffers
  particles_in[gidx] = particles_out[gidx];
}