#version 460 core
layout(local_size_x = 8, local_size_y = 8) in;

layout(rgba32f, binding = 0) uniform image2D fragColor;
layout(rgba32f, binding = 1) uniform image2D brightColor;
layout(rgba32f, binding = 2) uniform image2D imageOut;

void main() {
  ivec2 gidx = ivec2(gl_GlobalInvocationID.xy);

  vec3 color = imageLoad(fragColor, gidx).xyz + imageLoad(brightColor, gidx).xyz;

  imageStore(imageOut, gidx, vec4(color, 1.0));
}